##Let create a list - vertebrate
vertebrates = ["Human","Mouse","Cow","Chichen","Fugu","Zebrafish","Xenopus","Lion","Eel"]
## print this list
print(vertebrates)
print ("1st element of vertebrates:")
print(vertebrates[0])
print ("2nd element of vertebrates:")
print(vertebrates[1])
print ("3rd element of vertebrates:")
print(vertebrates[2])
print ("4th element of vertebrates:")
print(vertebrates[3])
print ("5th element of vertebrates:")
print(vertebrates[4])
print ("6th element of vertebrates:")
print(vertebrates[5])
print ("7th element of vertebrates:")
print(vertebrates[6])
print ("8th element of vertebrates:")
print(vertebrates[7])
print ("9th element of vertebrates:")
print(vertebrates[8])
print ("-1 element of vertebrates:")
print(vertebrates[-1])
print ("-5 element of vertebrates:")
print(vertebrates[-5])
print ("-9 element of vertebrates:")
print(vertebrates[-9])
print ("last element of vertebrates:")
print(vertebrates[-9])
